server:
  port: 10001
dubbo:
  application:
    name: user-rpc-dubbo-consumer
    register-consumer: true
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 1000
    retries: 3
